# Generated by Django 3.2 on 2021-04-18 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctormodel',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
