# Generated by Django 3.2 on 2021-04-17 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissionmodel',
            name='admission_date',
            field=models.DateField(auto_now=True),
        ),
    ]
