# Generated by Django 3.2 on 2021-04-21 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_main', '0003_alter_appointmentmodel_serial_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentmodel',
            name='appointment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
