# Generated by Django 3.2 on 2021-04-22 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App_main', '0005_auto_20210422_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dischargemodel',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='discharge_patient', to='App_main.admissionmodel'),
        ),
    ]
