# Generated by Django 3.2 on 2021-04-22 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_main', '0006_alter_dischargemodel_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dischargemodel',
            name='assigned_Doctor',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='dischargemodel',
            name='patient',
            field=models.CharField(max_length=100),
        ),
    ]
