# Generated by Django 3.2 on 2021-04-22 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_main', '0008_alter_admissionmodel_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dischargemodel',
            name='releaseDate',
            field=models.DateField(auto_now=True),
        ),
    ]
