# Generated by Django 3.2 on 2021-04-22 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_main', '0009_alter_dischargemodel_releasedate'),
    ]

    operations = [
        migrations.AddField(
            model_name='dischargemodel',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
